version: "3.9"
networks:
  traefiknet:
    driver: bridge
services:
  nginx:
    image: nginx:stable-alpine
    deploy:
      replicas: 2
    ports:
       - 80
    volumes:
      - "nginx/logs/:/var/log/nginx/"
    labels:
      - traefik.enable=true
      - traefik.http.routers.apache.rule=Host(`nginx.labtraefik.local`)
      - traefik.http.routers.apache.entrypoints=web
      - traefik.port=80
    networks:
      - traefiknet
  traefik:
    restart: always
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`proxy.labtraefik.local`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.service=api@internal
      - traefik.port=8080"
    networks:
      - traefiknet
    depends_on:
      - nginx
